---
framework: mocha
preRun:
     command:
        - npm i
preMerge:
  pattern:
    - "test/test.ts"
postMerge:
  pattern:
    - "test/test.ts"
postRun:
     command:
        - node --version
parallelism: 2
version: 1.0
